# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ceb8c9a693c5dc3411501786102de4c50e735d1254a20f063c3b55dccd1c6fd3d604e57e350e4fde5dbacdc92b54c4e7f17dfa84867686f71524e8c10580cd7

test:
  secret_key_base: d84b18d5149a499be1be285e83cc154ba8638ac72cd55b16c0d0f9716a3ef7530b0106cef373dc35aff8b8b99c00ba7906c9e1a2013a503e6513ec7b478e3db0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
